# Configuration for training detector

# Model architecture
model:
  in_channels: 64
  hidden_channels: 128
  embedding_dim: 64
  gru_hidden_dim: 128
  num_heads: 8
  num_layers: 3
  gru_layers: 2
  dropout: 0.3

# Training parameters
training:
  learning_rate: 0.001
  batch_size: 32
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # Loss weights
  reconstruction_weight: 1.0
  feature_weight: 0.1

# Data
data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  num_workers: 4
  pin_memory: true

# Checkpointing
checkpoint:
  dirpath: "checkpoints/"
  filename: "causaldefend-{epoch:02d}-{val_f1:.3f}"
  save_top_k: 3
  monitor: "val_f1"
  mode: "max"

# Early stopping
early_stopping:
  monitor: "val_f1"
  patience: 15
  mode: "max"

# Logging
logging:
  project: "causaldefend"
  name: "apt-detector"
  log_every_n_steps: 50

# Hardware
trainer:
  accelerator: "gpu"
  devices: 1
  precision: 16-mixed
  deterministic: false
